<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\User;
use App\Perpus;
use App\Video;
use App\JenisStase;
use App\Stase;
use Storage;

class test extends Command
{
    /**
     * The name and signature of the console command.
     *

class test extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:test';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
		$data =
		[
			"AMILOIDOSIS DARI KULIT .docx",
			"CarryItEasy.exe",
			"Chapter 135-GANGGUAN SANTOMATOSIS DAN LIPOPROTEIN.docx",
			"Chapter 136-PENYAKIT FABRY .docx",
			"Chapter 137-PROTEINOSIS LIPOID DAN DIWARISKAN GANGGUAN JARINGAN IKAT .docx",
			"Chapter 138-MINERALISASI DAN OSIFIKASI KUTIS .docx",
			"Chapter 139-GANGGUAN TURUNAN DARI KETIDAKSTABILAN GENOME DAN PERBAIKAN DNA .docx",
			"Chapter 140-TUBEROUS SKELROSIS KOMPLEKS .docx",
			"Chapter 141-THE NEUROFIBROMATOSES .docx",
			"Chapter 142-DISPLASIA EKTODERMAL.doc",
			"Chapter 143-PENYAKIT IMUNODEFISIENSI GENETIK.docx",
			"Chapter 144-MANIFESTASI KULIT DARI GANGGUAN SUMSUM TULANG ATAU GANGGUAN KIMIAWI DARAH.docx",
			"Chapter 145-LIMFOMA KUTANEUS.docx",
			"Chapter 146-PENYAKIT PERADANGAN YANG MENYERUPAI LIMFOMA.docx",
			"Chapter 147-HISTIOSITOSIS SEL LANGERHANS KUTANEUS.docx",
			"Chapter 148-HISTIOSITOSIS SEL NON-LANGERHANS.docx",
			"Chapter 149-MASTOSITOSIS.docx",
			"Chapter 150-MANIFESTASI-MANIFESTASI KULIT DARI KELAINAN-KELAINAN ORGAN DALAM.docx",
			"Chapter 151-DIABETES MELITUS DAN PENYAKIT ENDOKRIN.docx",
			"Chapter 152-SARKOIDOSIS.docx",
			"Chapter 153-MANIFESTASI-MANIFESTASI KUTAN KEGANASAN ORGAN-ORGAN DALAM .docx",
			"Chapter 154-KULIT PADA KELAINAN JARINGAN,VASKULAR SERTA KELAINAN AUTOIMUN.docx",
			"Chapter 155-LUPUS ERITEMATOSUS.doc",
			"Chapter 156-DERMATOMIOSITIS.docx",
			"Chapter 157-SKLERODERMA.docx",
			"Chapter 158-SKLEREDEMA DAN SKLEROMIKSEDEMA.docx",
			"Chapter 159-POLICHONDRITIS YANG RELAPS?RELAPSING POLICHONDRITIS.docx",
			"Chapter 160- Artritis Rematoid, Demam Rematik, dan Gout.docx",
			"Chapter 161-SINDROMA SJOGREN.docx",
			"Chapter 162-KULIT PADA KELAINAN-KELAINAN INFLAMATORI DAN VASKULAR LAINNYA.docx",
			"Chapter 163-Venulitis Kutaneus Nekrotikan (Cutaneus Necrotizing venulitis).docx",
			"Chapter 164-SYSTEMIC NECROTIZING ARTERITIS (ARTERITIS NEKROTIKAN SISTEMIK).docx",
			"Chapter 165-ERYTHEMA ELEVATUM DIUTINUM.docx",
			"Chapter 166-PENYAKIT ADAMANTIADES-BECHET.docx",
			"Chapter 167-PENYAKIT KAWASAKI.docx",
			"Chapter 168-DERMATOSIS PURPURA BERPIGMEN.docx",
			"Chapter 169-KRIOGLOBULINEMIA DAN KRIOFIBRINOGENEMIA.docx",
			"Chapter 170-FENOMENA RAYNAUD.docx",
			"Chapter 174-PERUBAHAN KUTANEUS PADA VENA PERIFER DAN INSUFISIENSI SISTEM LIMFATIK.docx",
			"Chapter 175-PENYAKIT YANG BERKAITAN DENGAN AGEN MIKROBIAL, INFESTASI, GIGITAN, DAN SENGATAN.docx",
			"Chapter 176-INFEKSI KULIT SUPERFISIAL DAN PIODERMA.docx",
			"Chapter 177-INFEKSI GRAM POSITIF BERKAITAN DENGAN PRODUKSI TOKSIN.docx",
			"Chapter 178.docx",
			"Chapter 179.docx",
			"Chapter 180.docx",
			"Chapter 181.docx",
			"Chapter 182.doc",
			"Chapter 184.doc",
			"Chapter 185.doc",
			"Chapter 186.docx",
			"Chapter 187.docx",
			"Chapter 188.docx",
			"Chapter 189.docx",
			"Chapter 190.docx",
			"Chapter 193.docx",
			"Chapter 196.docx",
			"Chapter 197.docx",
			"Chapter 198.docx",
			"Chapter 199.docx",
			"Chapter 200.docx",
			"Chapter 201.docx",
			"Chapter 202 .docx",
			"Chapter 203.docx",
			"Chapter 204.docx",
			"Chapter 205.docx",
			"Chapter 206.docx",
			"Chapter 207.docx",
			"Chapter 208.docx",
			"Chapter 209.docx",
			"Chapter 210.docx",
			"Chapter 211.docx",
			"Chapter 212.docx",
			"Chapter 213.docx",
			"Chapter 214.docx",
			"Chapter 215.docx",
			"Chapter 216.docx",
			"Chapter 217.docx",
			"Chapter 218.docx",
			"Chapter 219.docx",
			"Chapter 220.docx",
			"Chapter 221.docx",
			"Chapter 222.docx",
			"Chapter 223.docx",
			"Chapter 224.docx",
			"Chapter 226.docx",
			"Chapter 227.docx",
			"Chapter 228.docx",
			"Chapter 229.docx",
			"Chapter 230.docx",
			"Chapter 231.docx",
			"Chapter 232.docx",
			"Chapter 233.docx",
			"Chapter 234.docx",
			"Chapter 236.docx",
			"Chapter 237.docx",
			"Chapter 238.docx",
			"Chapter 239.docx",
			"Chapter 240.docx",
			"Chapter 241.docx",
			"Chapter 242.docx",
			"Chapter 243.docx",
			"Chapter 244.docx",
			"Chapter 245.docx",
			"Chapter 246.docx",
			"Chapter 247.docx",
			"Chapter 248.docx",
			"Chapter 249.docx",
			"Chapter 250.docx",
			"Chapter 251.docx",
			"Chapter 252.docx",
			"Chapter 253.docx",
			"Chapter 254.docx",
			"Chapter 255.docx",
			"Chapter 256.docx",
			"COVER.docx",
			"drPuguh COSMIC Maret.docx",
			"f.txt",
			"fe.txt",
			"fitzpatrick's ed.8th.PDF",
			"hari ke-1",
			"hari ke-2",
			"KELAIANAN KULIT AKIBAT GANGGUAN METABOLISME ASAM AMINO.docx",
			"KULIT PADA PENYAKIT NUTRISIONAL, METABOLIK DAN DITURUNKAN.docx",
			"PENYAKIT SISTEMIK AUTOINFLAMASI.docx",
			"Philips UFD User Guide-APAC.PDF",
			"PORFIRIA .docx",
			"Proposal Bab 3.docx",
			"threadlift",
			"TP Luka & Ulkus.pptx",
			"TP virus herpes humanus fix.docx",
			"video facial",
			"Videos",
			"1. BSS peraturan perundangan pendukung, dr.Tjut.pptx",
			"2. CV dr. Andy.pptx",
			"3. LOCAL  ANAESTHESIA, Prof. endangpptx.pptx",
			"6. Hemostasis, dr. Asmaja DS SpKK.ppt",
			"Anestesi Tumesen - Adhi.pptx",
			"Anestesi Unpad BLS 2015.wmv",
			"Block anesthesia - edit.pptx",
			"LOCAL  ANAESTHESIA, Prof. endangpptx.pptx",
			"Pelatihan Bedah Dasar-BSSKulit.pdf",
			"peraturan perundangan pendukung, dr.Tjut.pptx",
			"VIDEO",
			".DS_Store",
			"._.DS_Store",
			"09-ReefKnotInstrumen.mpg",
			"11-SurgeonKnot.mpg",
			"12-SlipKnot.mpg",
			"Instrumen",
			"Scrubbing, Gloving, Gowning .mpg",
			"Suturing",
			"Tehnik Simpul",
			"06-InstrumenHandling.mpg",
			"Pisau-pasang mata.MPG",
			"._19-Subcuticular Sutures.MPG",
			"._Koreksi dog ear.MPG",
			"15-InterrupturedSuture.mpg",
			"16-Continuous Suture.MPG",
			"17-The Art of Assisting.MPG",
			"18-Mattress Suture.MPG",
			"19-Subcuticular Sutures.MPG",
			"Koreksi dog ear.MPG",
			"._2 Hand jari tengah kanan.mpg",
			"._surgeon sekaligus1.mpg",
			"1 hand kanan telunjuk.mpg",
			"1 hand kanan tengah.mpg",
			"1 hand kiri telunjuk.mpg",
			"1 hand kiri tengah.mpg",
			"2 Hand jari tengah kanan.mpg",
			"2 hand jari tengah kiri.mpg",
			"2 hand Telunjuk kanan.mpg",
			"2 Hand trekunjuk kiri.mpg",
			"surgeon sekaligus.mpg",
			"surgeon sekaligus1.mpg",
			"surgeon telunjuk.mpg",
			"surgeon tengah 1 hand.mpg",
			"surgeon tengah.mpg",
			"14-Suture&Technology.mpg",
			"15-InterrupturedSuture.mpg",
			"16a ContiuousSuture.mpg",
			"18-Mattress Suture.MPG",
			"19-Subcuticular Sutures.MPG",
			"FLAP",
			"Safe Surgery Jakarta 2016.pptx",
			"Flap BSS 2016",
			"PRAKTIKUM FLAP",
			"._cosunit.mov",
			"._Flap BSS 2016.pptx",
			"._trasnflap.mp4",
			"cosunit.mov",
			"Flap BSS 2016.pptx",
			"SANY0004.MP4",
			"trasnflap.mp4",
			"._ADV PRAK",
			"._ISLAND FLAP PRAK",
			"._ROT PRAK",
			"._TRANS PRAK",
			"._VT PRAK",
			"._VY PLAS PRAK",
			"._Z PLAS PRAK",
			"ADV PRAK",
			"FLAP DESIGN",
			"ISLAND FLAP PRAK",
			"ROT PRAK",
			"TRANS PRAK",
			"VT PRAK",
			"VY PLAS PRAK",
			"Z PLAS PRAK",
			"._ADV PRAK.pptx",
			"ADV PRAK.pptx",
			"PRAKTIKUM FLAP.pptx",
			"._cosunit.mov",
			"._FLAP DESIGN.pptx",
			"._trasnflap.mp4",
			"cosunit.mov",
			"FLAP DESIGN.pptx",
			"SANY0004.MP4",
			"trasnflap.mp4",
			"._ISLAND FLAP PRAK.pptx",
			"._ROT PRAK.pptx",
			"ROT PRAK.pptx",
			"._TRANS PRAK.pptx",
			"._vir limberg flap.mp4",
			"._vir rhom flap.mp4",
			"TRANS PRAK.pptx",
			"vir limberg flap.mp4",
			"vir rhom flap.mp4",
			"._VT PRAK.pptx",
			"VT PRAK.pptx",
			"._VY PLAS PRAK.pptx",
			"VY PLAS PRAK.pptx",
			"._vir z plas.mp4",
			"._Z PLAS PRAK.pptx",
			"vir z plas.mp4",
			"Z PLAS PRAK.pptx",
			"IndexerVolumeGuid",
			"WPSettings.dat",
			"IMG_6554.JPG",
			"IMG_6555.MOV",
			"facial tutorial",
			"IMG_2623.MOV",
			"IMG_2624.MOV",
			"IMG_2625.MOV",
			"IMG_2626.MOV",
			"IMG_2627.MOV",
			"IMG_2628.MOV",
			"IMG_2629.MOV",
			"IMG_2630.MOV",
			"IMG_2631.MOV",
			"IMG_2632.JPG",
			"IMG_2633.MOV",
			"IMG_2634.MOV",
			"IMG_2635.JPG",
			"video osce",
			"---3 Interrupted Sutures- Simple, Vertical Mattress, -u0026 Horizontal Mattress.mov - YouTube.mp4",
			"---Best Prostate Video.mp4",
			"---Digital rectal examination.mp4",
			"---HAND WASHING (cuci tangan 7 langkah dan bedah).mp4",
			"---JAHITAN BEDAH.wmv - YouTube.mp4",
			"---Male Foley Catheter - YouTube.mp4",
			"---Pemeriksaan Fisik Abdomen - YouTube.mp4",
			"---Prostate cancer- Essential facts.mp4",
			"---Running Subcuticular.mp4",
			"---Suturing a Wound - YouTube.mp4",
			"---ToucheRectal.flv.mp4",
			"---Tutorial PEMERIKSAAN FISIK ABDOMEN.mp4",
			"---vertical mattress suturing surgical operation.mp4",
			".dthumb",
			"Oska Kompre 08",
			"Pemasangan Kateter - Latihan - YouTube.mp4",
			"Pemasangan Kateter Wanitaflv - YouTube_2 - YouTube.mp4",
			"Pemeriksaan Fisik Abdomen dan Thorax FK UWKS 2013 - YouTube.mp4",
			"Skill Lab Blok 20- Pemasangan Kateter (Part 2) - YouTube.mp4",
			"skill lab px payudara - YouTube.mp4",
			"-1306714265.dthumb",
			"-1351651825.dthumb",
			"-1628539700.dthumb",
			"-1859081546.dthumb",
			"-1974658289.dthumb",
			"-1990575351.dthumb",
			"-2087368862.dthumb",
			"-21676348.dthumb",
			"-364187211.dthumb",
			"-493357265.dthumb",
			"-655580328.dthumb",
			"1128897218.dthumb",
			"1318789931.dthumb",
			"1499909764.dthumb",
			"1685351463.dthumb",
			"388096880.dthumb",
			"432387351.dthumb",
			"717683281.dthumb",
			"000. Gambaran OSCE Compre 2005-2006-2007.ppt",
			"000. LATIHAN SOAL RESEP.ppt",
			"001. Anestesi",
			"002. Obsgyn",
			"003. THT",
			"004. Bedah",
			"005. Anak",
			"006. Dalam",
			"007. IKM",
			"008. Saraf",
			"009. Kulit dan Kelamin",
			"010. Mata",
			"011. Forensik",
			"012. Jiwa",
			"Bahan",
			"Ringkasan",
			"Soal 2008",
			".dthumb",
			"001. Airway Managment_ Non-Surgical.flv",
			"001. CPR.mpg",
			"001. Decompressing A Tension Pneumothorax.flv",
			"001. Initial Assessment of a Trauma Patient - Normal Scenario (with possible pathology).flv",
			"001. Intravenous line insertion.flv",
			"001. INTUBASI.mpg",
			"001. Male Urethral Catheterization.flv",
			"001. Nasogastric tube insertion.flv",
			"001. POLI ANESTESI GD 1.pptx",
			"001. POLI ANESTESI GD 2.pptx",
			"001. POLI ANESTESI GD 3.pptx",
			"-1093532362.dthumb",
			"-588440708.dthumb",
			"-881515735.dthumb",
			"1232343877.dthumb",
			"1460193873.dthumb",
			"1761273811.dthumb",
			"Ginekologi",
			"Obstetri",
			".dthumb",
			"002. Ginekologi.pptx",
			"002. Inspikulo - Sondase.mp4",
			"002. Speculum Examination.flv",
			"002. ASUHAN PERSALINAN NORMAL.DAT",
			"002. KALA 2-4.docx",
			"002. Obsgin.pptx",
			"003. Bahan Compre 2008 Modul THT.docx",
			"003. KASUS 1 OMA SUPURASI.pptx",
			"003. KASUS 2 RINITIS ALERGI.pptx",
			"003. KASUS 3 SINUSITIS.pptx",
			"003. KASUS 4 EPISTAKSIS.pptx",
			"003. KASUS 5 BENDA ASING HIDUNG.pptx",
			"003. KASUS 6 POLIP.pptx",
			"003. KASUS 7 VERTIGO.pptx",
			"003. KASUS 8 LARINGITIS.pptx",
			"003. PERBEDAAN.docx",
			"003. POLI THT.docx",
			"003. PRESENTASI OMA & RINOSINUSITIS.pptx",
			"003. RINITIS DD.docx",
			"003. RINITIS.pptx",
			"003. RINOSKOPI ANTERIOR.docx",
			"003. STADIUM OMA.docx",
			"004. Anamnesis payudara.docx",
			"004. JAHIT LUKA.docx",
			"004. Obturator Sign.flv",
			"004. Obturator Sign.wmv",
			"004. PF payudara.docx",
			"004. RECTAL TOUCHER.docx",
			"004. STATION BEDAH 2008.pptx",
			"PEMERIKSAAN PAYUDARA",
			"Video Hecting",
			"004. PEMERIKSAAN PAYUDARA.mpg",
			"004. Continuous Suture.mpg - YouTube_2.flv",
			"004. Horizontal Mattress Suturing - YouTube.flv",
			"004. Interlocking Continuous Suture - YouTube.flv",
			"004. Vertical Mattress Suturing - YouTube.flv",
			"005. POLI PEDIATRI PV 0.pptx",
			"005. POLI PEDIATRI PV 1.pptx",
			"005. POLI PEDIATRI PV 2.pptx",
			"005. POLI PEDIATRI PV 3.pptx",
			"005. POLI PEDIATRI PV 4.pptx",
			"005. TB ANAK.docx",
			"006. Dalem 1 Kardio.ppt",
			"006. Dalem 2 DM.ppt",
			"006. Dalem 3 Hepar.ppt",
			"006. Dalem 4 TB.ppt",
			"006. Dalem 5 Tambahan.ppt",
			"006. Modul Pencernaan.mpg",
			"006. Pemeriksaan Fisik Thorax Dasar.mpg",
			"suNtik iNsuLin",
			"Accu-Chek Demo (E)",
			"Huma Pen",
			"modules",
			"step01.swf",
			"step02.swf",
			"step03.swf",
			"step04.swf",
			"step05.swf",
			"step06.swf",
			"step07.swf",
			"step08.swf",
			"step09.swf",
			"swf",
			"step01.swf",
			"step02.swf",
			"step03.swf",
			"step04.swf",
			"step05.swf",
			"step06.swf",
			"step07.swf",
			"step08.swf",
			"step09.swf",
			"step10.swf",
			"animations.swf",
			"Autorun.inf",
			"modules",
			"Shortcut to CD Drive.lnk",
			"animations.swf",
			"animations.swf",
			"Autorun.inf",
			"modules",
			"Shortcut to CD Drive.lnk",
			"animations.swf",
			"007. CONTOH KASUS I.ppt",
			"007. CONTOH KASUS II.ppt",
			"007. IKM.docx",
			"007. POLI IKM-COMPRE2008.ppt",
			"008. MENINGITIS.pptx",
			"008. PEMERIKSAAN MOTORIK, SENSORIK, ROM.pptx",
			"008. PEMERIKSAAN NERVUS CRANIALIS.pptx",
			"008. PEMERIKSAAN REFLEK PATOLOGIS.pptx",
			"008. REFLEK FISIOLOGIS.pptx",
			"008. STROKE.pptx",
			"009. Kusta.ppt",
			"009. latihan 1.ppt",
			"009. latihan 2 dan 4.pptx",
			"009. latihan 3.ppt",
			"009. latihan 5.pptx",
			"009. latihan 6.ppt",
			"kusta",
			"poli kulkel",
			"009. Kusta 1.pdf",
			"009. Kusta 2.pdf",
			"009. Kusta 3.pdf",
			"009. Kusta 4.pdf",
			"009. gambar kuman2.doc",
			"009. latihan UKK tambahan.ppt",
			"009. Prick test dan Intra Dermal test.mpg",
			"009. UKK DERMATITIS.ppt",
			"009. UKK ERITROPAPULOSKUAMOSA&PIODERMA.pps",
			"009. UKK PRIMER DAN SEKUNDER.ppt",
			"latihan 1.ppt",
			"latihan 2 dan 4.pptx",
			"latihan 3.ppt",
			"latihan 5.pptx",
			"010. Latihan Kasus Poli Mata.ppt",
			"010. OSCE Kompre Poli Mata.ppt",
			"katarak n glaukoma",
			"010. GLAUKOMA.pptx",
			"010. KASUS 2.pptx",
			"010. Kasus 3.pptx",
			"010. kasus 5.pptx",
			"010. katarak okk.pptx",
			"010. TEKANAN BOLA MATA.mpg",
			"011. Analisis kasus tenggelam by Adit.docx",
			"011. FORENSIK KASUS TENGGELAM.pptx",
			"011. Format VeR.docx",
			"011. G. Pengambilan Sampel Toksikologi.ppt",
			"011. kasus 3.docx",
			"011. KASUS VISUM.docx",
			"011. keracunan by agri.docx",
			"011. luka robek.doc",
			"011. Materi Tambahan.pptx",
			"011. THANATOLOGI.ppt",
			"011. TOKSIKOLOGI.ppt",
			"011. VeR Hidup.pptx",
			"011. VeR Inem.docx",
			"011. VeR Jenazah Luka tusuk perut.doc",
			"011. VeR Jenazah.pptx",
			"article-2051361-0E76195600000578-42_634x490.jpg",
			"Contoh Deskripsi Luka dan Kesimpulan VeR",
			"luka bakar.jpg",
			"sex abuse.jpg",
			"tattoo1.jpg",
			"The National Center for Victims of Crime - Library Document Viewer.htm",
			"The National Center for Victims of Crime - Library Document Viewer_files",
			"Deskripsi Luka 1.jpg",
			"Deskripsi Luka 10.jpg",
			"Deskripsi Luka 2.jpg",
			"Deskripsi Luka 3.jpg",
			"Deskripsi Luka 4.jpg",
			"Deskripsi Luka 5.jpg",
			"Deskripsi Luka 6.jpg",
			"Deskripsi Luka 7.jpg",
			"Deskripsi Luka 8.jpg",
			"Deskripsi Luka 9.jpg",
			"Kesimpulan 1.jpg",
			"Kesimpulan 2.jpg",
			"Kesimpulan 3.jpg",
			"Kesimpulan 4.jpg",
			"Kesimpulan 5.jpg",
			"Kesimpulan 6.jpg",
			"Kesimpulan 7.jpg",
			"Kesimpulan 8.jpg",
			"about_title_list.gif",
			"AlfaEditors.js",
			"ClientLib.js",
			"ga.js",
			"Logo.gif",
			"powered_by_WebAssembler.NET.gif",
			"print.gif",
			"right_corner.gif",
			"012. DepResi OK.pptx",
			"012. GANGGUAN MOOD AFEK (LBM 2).docx",
			"012. GANGGUAN MOOD COMPRE.pptx",
			"012. GANGGUAN NEUROSIS (LBM 4).docx",
			"012. GANGGUAN PERKEMBANGAN PERVASIF (LBM 5).docx",
			"012. GANGGUAN PSIKOTIK (LBM 1).docx",
			"012. kasus skizofrenia.docx",
			"012. OBAT-OBAT PSIKIATRI.docx",
			"012. PROSES DIAGNOSIS GANGGUAN JIWA (SKILL).docx",
			"012. SIMTOMATOLOGI.docx",
			"012. SKIZOFRENIA PRESENTASI COMPRE.pptx",
			"SGD 08",
			"SKILL 08",
			"002. Obsgyn.rtf",
			"003. THT.doc",
			"004. Bedah.docx",
			"005. Anak.docx",
			"006. Dalam.docx",
			"007. IKM.doc",
			"008. Saraf.docx",
			"009. Kulit dan Kelamin.docx",
			"010. Mata.docx",
			"012. Jiwa.docx",
			"000. Daftar Isi.docx",
			"001. Anestesi.docx",
			"002. Obsgyn.docx",
			"003. THT.docx",
			"004. Bedah.docx",
			"005. Anak.docx",
			"006. Dalam.docx",
			"007. IKM.docx",
			"008. Saraf.docx",
			"009. Kulit dan Kelamin 1.docx",
			"009. Kulit dan Kelamin 2.docx",
			"010. Mata.docx",
			"011. Forensik.docx",
			"012. Jiwa.docx",
			"001. Anestesi.docx",
			"002. Obsgin.docx",
			"003. THT.docx",
			"004. Bedah.docx",
			"005. Anak.docx",
			"001. Anestesi 1.pptx",
			"001. Anestesi 2.pptx",
			"002. Obsgyn konseling kb, akdr dan infertil.pptx",
			"002. Obsgyn.pptx",
			"003. THT OTITTS EKSTERNA AKUTA.pptx",
			"005. Anak review.pptx",
			"006. Dalam Cardio.ppt",
			"006. Dalam DIABETES MELLITUS.ppt",
			"006. Dalam DM tipe I.ppt",
			"006. Dalam Hepatitis.pptx",
			"006. Dalam Insulin Hormone.ppt",
			"006. Dalam komplikasi akut DM.ppt",
			"007. IKM compre PV.ppt",
			"008. Saraf - tyas.pptx",
			"008. Saraf NEUROLOGI.pptx",
			"009. Kulit dan Kelamin gambar latihan compre fix kuit.ppt",
			"009. Kulit dan Kelamin go&herpes+scabies.ppt",
			"009. Kulit dan Kelamin POLI KULIT KELAMIN.pptx",
			"010. Mata.ppt",
			"011. Forensik KASUS TENGGELAM.pptx",
			"011. Forensik Materi Tambahan.pptx",
			"011. Forensik Pembuatan visum et repertum.pptx",
			"011. Forensik VeR Review.pptx",
			"012. Jiwa.ppt"
		];

		$dataInsert = [];
		$timestamp = date('Y-m-d H:i:s');
		
		foreach ($data as $d) {
			if ( Storage::cloud()->exists('video/' . $d) ) {
				$dataInsert[] = [
					'judul' => $d,
					'link_materi' => Storage::cloud()->url('video/' . $d),
					'nama_file_materi' => 'video/' . $d,
					'created_at' => $timestamp,
					'updated_at' => $timestamp
				];
			}
		}
		Video::insert($dataInsert);
    }
}
